In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], [3, 4]]
data_tensor = torch.tensor(data)
print(data_tensor, type(data_tensor))

tensor([[ 1,  2],
        [ 3,  4]]) <class 'torch.Tensor'>


In [3]:
data = [[1, 2], [3, 4], [5, 6]]
np_data = np.array(data)
print(np_data, type(np_data))
np_data_tensor = torch.from_numpy(np_data)
print(np_data_tensor, type(np_data_tensor))

[[1 2]
 [3 4]
 [5 6]] <class 'numpy.ndarray'>
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6]]) <class 'torch.Tensor'>


In [4]:
torch.zeros(5)

tensor([ 0.,  0.,  0.,  0.,  0.])

In [5]:
torch.ones(2, 2)

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [6]:
torch.rand(3, 3, 3)

tensor([[[ 0.6799,  0.7535,  0.5530],
         [ 0.7295,  0.3920,  0.8904],
         [ 0.2358,  0.0067,  0.3328]],

        [[ 0.6537,  0.6660,  0.1822],
         [ 0.1126,  0.0975,  0.6305],
         [ 0.2822,  0.6680,  0.0977]],

        [[ 0.1176,  0.6509,  0.3062],
         [ 0.9696,  0.2150,  0.3240],
         [ 0.7867,  0.5007,  0.2262]]])

In [7]:
zero_tensor = torch.zeros(3, 3)
ones_like_zeros = torch.ones_like(zero_tensor)

print(zero_tensor.shape, ones_like_zeros.shape)

torch.Size([3, 3]) torch.Size([3, 3])


In [8]:
zero_tensor[0]

tensor([ 0.,  0.,  0.])

In [9]:
ones_like_zeros[:, 0]

tensor([ 1.,  1.,  1.])

In [10]:
x = ones_like_zeros.detach()
print(x)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])


In [11]:
x[:, 0] * 5

tensor([ 5.,  5.,  5.])

In [12]:
rand1 = torch.rand(5)
rand2 = torch.rand(5)
torch.matmul(rand1, rand2)

tensor(1.5430)

In [13]:
rand1 = torch.rand(5, 5)
rand2 = torch.rand(5, 5)
torch.matmul(rand1, rand2)

tensor([[ 1.6991,  0.5884,  1.4833,  0.9317,  2.0054],
        [ 2.0325,  1.1057,  1.6101,  1.3284,  1.9362],
        [ 1.5369,  0.5920,  1.2642,  0.8522,  1.5830],
        [ 1.0669,  0.6153,  1.3119,  1.1433,  1.4505],
        [ 1.9950,  1.1305,  1.6374,  1.3319,  2.1506]])